### ISSUE TITLE
K-9 coudn't decode e-mail

### ISSUE THREAD

**Issue by Jentsch** [afremize/afremize#1]
Hi,
I tried this nice service and it created a beautiful image. Unfortunately K-9 (an Android E-Mail client) wasn't able to recognize the attachment. I'm not an e-mail expert but may be this could be easily fixed.

Screen shot of K-9:
![2016-01-07 09 49 05](https://cloud.githubusercontent.com/assets/818446/12182093/673d6c80-b586-11e5-882a-be81c97efc90.png)

**Comment by Jane333** [comment]
Hi Jentsch,

yep, I noticed this happening with some e-mail accounts. It usually happens with yahoo (however, gmail, zoznam and others have no problems). I haven't had time to look into it just yest. Please, try another e-mail account in the meantime.
I'm a bit confused - have you actually tried both running the python scripts locally AND using the web interface at afremize.mynery.eu or afremize.com? How did you find the web interface? Not even Google has caught up on it yet...

**Comment by afremize** [comment]
Hi Jentsch,

yep, I noticed this happening with some e-mail accounts. It usually happens with yahoo (however, gmail, zoznam and others have no problems). I haven't had time to look into it just yest. Please, try another e-mail account (or client) in the meantime.
I'm a bit confused - have you actually tried both running the python scripts locally AND using the web interface at afremize.mynery.eu or afremize.com? How did you find the web interface? Not even Google has caught up on it yet...
I'm glad you liked the picture:-).

**Comment by Jentsch** [comment]
Hi Jane,
sorry I missed to mention that I use also Thunderbird for the same account. In Thunderbird I have no problem at all with the attached image. It seems that this is a e-mail client problem. (Both Thunderbird and K-9 have the same IMAP configuration). I used afremize.com.

You gave me address personal yesterday while you prepared a Github presentation. My avatar doesn't locks _that_ bat. ;-)

**Comment by afremize** [comment]
About two minutes ago, I got the idea to actually click on your avatar and take a closer look. For the last two minutes, I was struggling to decide whether you are, indeed, the person I met yesterday, who claimed to be called "Daniel".
According to Google (and you), it seems like the attachment sending works only when the right version of mailx meets the right e-mail client. This will be hell to work around.

**Comment by Jentsch** [comment]
Maybe a got this wrong, but how you want to know which client the use have to choose the correct mailx version?

**Comment by afremize** [comment]
I misspoke.  I meant to say it might be impossible with mailx. This post makes it look rather bleak:

https://access.redhat.com/solutions/1136493
"mailx in RHEL 5 sometimes sends e-mails that are not compliant to applicable standards (most importantly RFC 2822). Such e-mails might be displayed correctly by coincidence though."

Especially the "by coincidence" part quite accurately describes the current situation. Maybe I'll have to move to some other program, we'll see. I'll let you know.

**Comment by Jentsch** [comment]
I hope this move will be not that difficult. Thx

**Comment by Jane333** [comment]
Hey Daniel,

this issue should be fixed now, could you maybe try to convert another image and tell me if K-9 could open it?
Thanks!

**Comment by Jentsch** [comment]
Works fine.

Thank you
